// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Batarilan_Exercise1.Data;

#nullable disable

namespace Batarilan_Exercise1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260520000000_addpcunits")]
    partial class addpcunits
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
